spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: oracle
    password: oracle
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database: ORACLE
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

urlscheme:
  multichief:
    construction:
      domain: http://localhost:8080/Gradle___ru_goryachev___MultiChiefConstruction_war/
      apiversion: api/v1/
      subdomain:
        bim: bims/
        eir: eirs/
        estimate: estimates/
        type: types/

    staff:
      domain: http://localhost:8080/Gradle___ru_goryachev___MultiChiefStaff_war/
      apiversion: api/v1/
      subdomain:
        employee: employees/